version: "3.5"
services:
  web:
    build:
        context: .
        dockerfile: docker/web/Dockerfile
    restart: on-failure
    volumes:
      - '.:/web'
    ports:
      - "3003:3003" # http server
